upload:
  path: ${UPLOAD_PATH:static}

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      jdbc:
        time_zone: ${TZ:Europe/Moscow}
      ddl-auto: ${SCHEMA_INIT:update}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:restaurant}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:0000}
  session:
    jdbc:
      initialize-schema: always
      table-name: spring_session
  freemarker:
    expose-request-attributes: true
  mail:
    active_url: ${ACTIVE_URL:http://localhost:8080}
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:test@mail.ru}
    #env variable
    password: ${EMAIL_PASSWORD:0000}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
